name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run check
      - run: npm run build
